/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HASIL.java
 *
 * Created on Oct 5, 2015, 5:23:11 PM
 */
package TUGAS1;

/**
 *
 * @author Toshiba
 */
public class HASIL extends javax.swing.JFrame {

    /** Creates new form HASIL */
    public HASIL() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dATA11 = new TUGAS1.DATA1();
        dATA21 = new TUGAS1.DATA2();
        dATA31 = new TUGAS1.DATA3();
        dATA41 = new TUGAS1.DATA4();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel1.setText("PILIH MENU PERHITUNGAN");

        jTabbedPane1.addTab("+", dATA11);
        jTabbedPane1.addTab("-", dATA21);
        jTabbedPane1.addTab("X", dATA31);
        jTabbedPane1.addTab(":", dATA41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HASIL().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private TUGAS1.DATA1 dATA11;
    private TUGAS1.DATA2 dATA21;
    private TUGAS1.DATA3 dATA31;
    private TUGAS1.DATA4 dATA41;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
